site_name: "Vertama: The Manuals"
# site_url: https://vertama-gmbh.github.io/
#
theme:
  name: 'material'
  highlightjs: true
  hljs_languages:
      - yaml
  locale: en
  titles_only: false
  collapse_navigation: false
  features:
    - navigation.sections
extra_css:
  - css/extra.css
  - css/pdf-print.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
plugins:
  #  - pdf-export:
  #    compbined: true
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid@11.4.0/dist/mermaid.esm.min.mjs
nav:
  - Home: index.md
  - Products:
     # - DIGG: []
     # - DIGT: []
     # - DIVI: []
     - DUBA:
       - "API Tutorial": "Products/DUBA/api-tutorial.md"
       - "api.yml (OpenAPI)": Products/DUBA/api.yml
       - "Swagger API Viewer": "https://editor.swagger.io/#/?import=https://vertama-gmbh.github.io/docs/Products/DUBA/api.yml"
     - ELIM:
       - "Flyer":
         - "Products/ELIM/onepager/OnePager (PNG).md"
         - "Products/ELIM/onepager/OnePager (HTML).md"
         - "Products/ELIM/onepager/OnePager.md"
     - "ELIM+":
       - "API Tutorial": "Products/ELIMPLUS/api-tutorial.md"
       - "api.yml (OpenAPI)": Products/ELIMPLUS/api.yml
       - "Swagger API Viewer": "https://editor.swagger.io/#/?import=https://vertama-gmbh.github.io/docs/Products/ELIMPLUS/api.yml"
  - Guides:
    - "Folder Sync Handbook": "how-to/folder-sync-handbuch.md"
  # - "Tutorials": []
  - "Background & Explanations":
    - "Security & Encryption":
      - "Multi-User Secret Sharing": "background-and-explanations/security-and-encryption/Multi-User Secret Sharing with Zero-Knowledge Architecture.md"
      - "Password-Based User Secrets Encryption": "background-and-explanations/security-and-encryption/Password-Based User Secrets Encryption with Derived Keys.md"
      - "Implementation Notes": "background-and-explanations/security-and-encryption/Implementation-Notes.md"
      - "API Usage Guide": "background-and-explanations/security-and-encryption/API-Usage-Guide.md"
  - Reference:
    - "Systemanforderungen": "Reference/system-requirements.md"
    - "Endpunkte & Infrastruktur": "Reference/endpoints-and-infrastructure.md"
  - About: about.md
