site_name: "Vertama: The Manuals"
# site_url: https://vertama-gmbh.github.io/
#
theme:
  name: 'material'
  highlightjs: true
  hljs_languages:
      - yaml
  locale: en
  titles_only: false
  collapse_navigation: false
  features:
    - navigation.sections
extra_css:
  - css/extra.css
  - css/pdf-print.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
plugins:
  #  - pdf-export:
  #    compbined: true
  - mermaid2:
      javascript: https://unpkg.com/mermaid@11.4.0/dist/mermaid.esm.min.mjs
  - search
  - with-pdf: # https://pypi.org/project/mkdocs-with-pdf/
      author: Vertama
      copyright: Copyright &copy; 2025, Vertama GmbH. All Rights Reserved.
      #
      #cover: false
      #back_cover: true
      #cover_title: TITLE TEXT
      cover_subtitle: Technische Dokumentation und Handb√ºcher zu den Vertama Diensten
      #custom_template_path: TEMPLATES PATH
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      #output_path: any-place/document.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
nav:
  - Home: index.md
  - Products:
     - DIGG: []
     - DIGT: []
     - DIVI: []
     - DUBA:
       - "API Tutorial": "Products/DUBA/api-tutorial.md"
       - "api.yml (OpenAPI)": Products/DUBA/api.yml
       - "Swagger API Viewer": "https://editor.swagger.io/#/?import=https://vertama-gmbh.github.io/docs/Products/DUBA/api.yml"
     - ELIM:
       - "Products/ELIM/onepager/OnePager (PNG).md"
       - "Products/ELIM/onepager/OnePager (HTML).md"
       - "Products/ELIM/onepager/OnePager.md"
  - Guides:
    - "Folder Sync Handbook": "how-to/folder-sync-handbuch.md"
  - "Tutorials": []
  - "Background & Explanations":
    - "Security & Encryption":
      - "Multi-User Secret Sharing": "background-and-explanations/security-and-encryption/Multi-User Secret Sharing with Zero-Knowledge Architecture.md"
      - "Password-Based User Secrets Encryption": "background-and-explanations/security-and-encryption/Password-Based User Secrets Encryption with Derived Keys.md"
      - "Implementation Notes": "background-and-explanations/security-and-encryption/Implementation-Notes.md"
      - "API Usage Guide": "background-and-explanations/security-and-encryption/API-Usage-Guide.md"
  - Reference: []
  - Downloads: download.md
  - About: about.md
